// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestTask.Infrastructure;

#nullable disable

namespace TestTask.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestTask.Core.Models.Entities.Meteorite", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("Fall")
                        .HasColumnType("int");

                    b.Property<double?>("Mass")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("NameType")
                        .HasColumnType("int");

                    b.Property<string>("RecClass")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("RecLat")
                        .HasColumnType("float");

                    b.Property<double?>("RecLong")
                        .HasColumnType("float");

                    b.Property<DateTime?>("Year")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("RecClass");

                    b.HasIndex("Year");

                    b.ToTable("Meteorites", (string)null);
                });

            modelBuilder.Entity("TestTask.Core.Models.Entities.Meteorite", b =>
                {
                    b.OwnsOne("TestTask.Core.Models.Entities.Geolocation", "Geolocation", b1 =>
                        {
                            b1.Property<int>("MeteoriteId")
                                .HasColumnType("int");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Geo_Type");

                            b1.HasKey("MeteoriteId");

                            b1.ToTable("Meteorites");

                            b1.WithOwner()
                                .HasForeignKey("MeteoriteId");

                            b1.OwnsOne("TestTask.Core.Models.Entities.Coordinates", "Coordinates", b2 =>
                                {
                                    b2.Property<int>("GeolocationMeteoriteId")
                                        .HasColumnType("int");

                                    b2.Property<double>("Lat")
                                        .HasColumnType("float")
                                        .HasColumnName("Geo_Lat");

                                    b2.Property<double>("Lon")
                                        .HasColumnType("float")
                                        .HasColumnName("Geo_Lon");

                                    b2.HasKey("GeolocationMeteoriteId");

                                    b2.ToTable("Meteorites");

                                    b2.WithOwner()
                                        .HasForeignKey("GeolocationMeteoriteId");
                                });

                            b1.Navigation("Coordinates")
                                .IsRequired();
                        });

                    b.Navigation("Geolocation");
                });
#pragma warning restore 612, 618
        }
    }
}
